project:
  type: book
  output-dir: docs

book:
  title: "R for Environmental Chemistry Data Analysis"
  author: "Thanh Wang"
  date: "2024-02-13"
  chapters:
    - index.qmd
    - 1_Basic_R.qmd
    - 2_Conditions_Loops.qmd
    - 3_Functions.qmd
    - 4_Tidyverse.qmd
    - Appendix_Version_control.qmd
    - Appendix_Quarto.qmd
    - Appendix_DatabaseDesign.qmd
    - Appendix_Kumla_PFAS.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

