project:
  type: book

book:
  title: "LiU PhD course: R for Environmental Chemistry Data Analysis"
  author: "Thanh Wang"
  date: "2024-02-05"
  chapters:
    - index.qmd
    - 1_Basic_R.qmd
    - Appendix_Version_control.qmd
    - Appendix_DatabaseDesign.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

